FROM python:3.6

# Rabbit
ARG RABBITMQ_USERNAME
ENV RABBITMQ_USERNAME=$RABBITMQ_USERNAME

ARG RABBITMQ_PASSWORD
ENV RABBITMQ_PASSWORD=$RABBITMQ_PASSWORD

ARG RABBITMQ_HOST
ENV RABBITMQ_HOST=$RABBITMQ_HOST

ARG RABBITMQ_PORT
ENV RABBITMQ_PORT=$RABBITMQ_PORT

ARG RABBITMQ_VIRTUAL_HOST
ENV RABBITMQ_VIRTUAL_HOST=$RABBITMQ_VIRTUAL_HOST

# Postgres
ARG POSTGRES_DB_USERNAME
ENV POSTGRES_DB_USERNAME=$POSTGRES_DB_USERNAME

ARG POSTGRES_DB_PASSWORD
ENV POSTGRES_DB_PASSWORD=$POSTGRES_DB_PASSWORD

ARG POSTGRES_DB_HOST
ENV POSTGRES_DB_HOST=$POSTGRES_DB_HOST

ARG POSTGRES_DB_PORT
ENV POSTGRES_DB_PORT=$POSTGRES_DB_PORT

ARG POSTGRES_DB_NAME
ENV POSTGRES_DB_NAME=$POSTGRES_DB_NAME

# Sentry
ARG SENTRY_DSN
ENV SENTRY_DSN=$SENTRY_DSN

# Domain
ARG DOMAIN
ENV DOMAIN=$DOMAIN

# Security
ARG HTTPS_ENABLED
ENV HTTPS_ENABLED=$HTTPS_ENABLED

RUN apt-get update
RUN apt-get install netcat -y

# Install requirements
COPY requirements* /tmp/
USER root
RUN pip install -r /tmp/requirements.txt

# Port
EXPOSE 8000

# Copy app
COPY ./src /app/src
COPY ./run.sh /app
COPY ./config.yaml /app

# Run
WORKDIR /app
CMD ["./run.sh"]
