"""Initial

Revision ID: 8faec89fb561
Revises: 
Create Date: 2020-12-06 13:18:41.558065

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '8faec89fb561'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sockets',
    sa.Column('socket_id', sa.String(length=256), nullable=False),
    sa.Column('expire', sa.DateTime(), nullable=False),
    sa.Column('user_uuid', sqlalchemy_utils.types.uuid.UUIDType(), nullable=False),
    sa.Column('channel', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('socket_id'),
    sa.UniqueConstraint('socket_id'),
    schema='websockets'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sockets', schema='websockets')
    # ### end Alembic commands ###
